### ISSUE TITLE
Detecting specific word sent by members of a discord server.

### ISSUE THREAD

**Issue by Swap-Nova** [anupammaurya6767/Botzy#1]
Programming the Discord Bot to detect specific words sent by the members in a server. 
Moreover, I handle message detection and responses responsibly and ensure they comply with Discord's Terms of Service and server rules. Additionally, we may want to implement proper error handling and logging to debug issues and improve the bot's reliability.

**Comment by Swap-Nova** [comment]
@anupammaurya6767  may you assign this issue to me?

**Comment by anupammaurya6767** [comment]
@Swap-Nova go ahead
